networks:
  presto:
    driver: bridge
    ipam:
      config:
        - subnet: 10.18.0.0/24
          gateway: 10.18.0.1

services:
  minio:
    hostname: minio-server
    image: 'minio/minio:latest'
    container_name: minio-server
    command: server --console-address ":9001" /minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ./minio/data:/minio
    networks:
      presto:
        ipv4_address: 10.18.0.2

  hadoop:
    hostname: hadoop-master
    image: 'prestodb/hive3.1-hive:10'
    container_name: hadoop-master
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ./hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
    ports:
      - 9083:9083
    depends_on:
      - minio
    networks:
      presto:
        ipv4_address: 10.18.0.3

  coordinator:
    container_name: coordinator
    image: prestodb/presto:latest
    platform: linux/amd64
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - 8080:8080
    volumes:
      - ./coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - ./catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
      - ./catalog/hive.properties:/opt/presto-server/etc/catalog/hive.properties
      - ./datagen/create-tpcds-sf1-parquet-hive.sql:/opt/create-tpcds-sf1-parquet-hive.sql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.18.0.8:8080"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      presto:
        ipv4_address: 10.18.0.8

  worker_1:
    container_name: worker_1
    image: prestodb/presto:latest
    platform: linux/amd64
    restart: always
    depends_on:
      - coordinator
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./workers/1/node.properties:/opt/presto-server/etc/node.properties
      - ./catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - ./catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
      - ./catalog/hive.properties:/opt/presto-server/etc/catalog/hive.properties
    networks:
      presto:
        ipv4_address: 10.18.0.18

  worker_2:
    container_name: worker_2
    image: prestodb/presto:latest
    platform: linux/amd64
    restart: always
    depends_on:
      - coordinator
    deploy:
      resources:
        limits:
          memory: 4G
    volumes:
      - ./workers/config.properties:/opt/presto-server/etc/config.properties
      - ./workers/jvm.config:/opt/presto-server/etc/jvm.config
      - ./workers/2/node.properties:/opt/presto-server/etc/node.properties
      - ./catalog/jmx.properties:/opt/presto-server/etc/catalog/jmx.properties
      - ./catalog/tpcds.properties:/opt/presto-server/etc/catalog/tpcds.properties
      - ./catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
      - ./catalog/hive.properties:/opt/presto-server/etc/catalog/hive.properties
    networks:
      presto:
        ipv4_address: 10.18.0.28
